### ISSUE TITLE
What are some must-watch/read resources to get into business process modelling (DDD, OOD, ?)? 

### ISSUE THREAD

**Issue by mr-mig** [practicingdev/ama#2]

**Comment by practicingdev** [comment]
I have to confess, I've done so much of this by way of "learning on the job" that I've done very little formal reading on the topic... and that's a weak spot of mine. This is why I'm trying to jump into DDD with both feet, and beginning the book from Eric Evans which seems to be the canonical starting point.

I've also loosely been collaborating with Mel Conway, who in addition to coining Conway's Law, has been working on some very interesting research around building new workflows for developers that would make application development feel much more natural... which would in turn increase the ability for domain experts to directly contribute to applications, or at least work with a developer in realtime with very tight feedback loops.

An overview of his ideas can be found in [this paper](http://melconway.com/Home/pdf/modeless.pdf).

But as I said, this is an area I've done a bad job studying from a formal angle, and so I'd like to turn the question around to you and see what you'd recommend. 😄
